require "spec_helper"

describe Tacokit::Client::Checklists do
  def test_checklist_id
    "548ddd3f5402eb674035334f"
  end

  def test_card_id
    "548dd95c8ca25ac9d0d9ce71"
  end

  describe "#checklist", :vcr do
    it "returns a checklist by id" do
      checklist = app_client.checklist(test_checklist_id)

      expect(checklist.name).to eq "Checklist 1"
    end
  end

  describe "#update_checklist", :vcr do
    it "updates a checklist" do
      checklist = app_client.update_checklist test_checklist_id,
        name: "Test Checklist 1"

      expect(checklist.name).to eq "Test Checklist 1"
      assert_requested :put, trello_url_template("checklists/#{test_checklist_id}{?key,token}")
    end
  end

  describe "#check_items", :vcr do
    before do
      @card = app_client.create_card test_list_id, "Autocard", desc: "This is an autogenerated card"
      @checklist = app_client.start_checklist(@card.id, "Making a list")
    end

    it "retrieves checklist check items" do
      app_client.add_checklist_item(@checklist.id, "Test Checklist Item")

      check_items = app_client.check_items(@checklist.id)

      expect(check_items.size).to eq(1)
      expect(check_items.first.name).to eq("Test Checklist Item")
    end

    it "adds a checklist check item" do
      item = app_client.add_checklist_item(@checklist.id, "Test Checklist Item")

      expect(item.name).to eq("Test Checklist Item")
    end

    after do
      app_client.delete_card(@card.id)
    end
  end

  describe "#create_checklist", :vcr do
    before do
      @checklist = app_client.create_checklist test_card_id, "Autochecklist", pos: "top"
    end

    it "creates a checklist" do
      expect(@checklist.name).to eq "Autochecklist"
      expect(@checklist.pos).to be >= 1
      assert_requested :post, trello_url_template("checklists{?key,token}"),
        body: {
          "name" => "Autochecklist",
          "pos" => "top",
          "idCard" => test_card_id
        }
    end

    after do
      app_client.delete_checklist(@checklist.id)
    end
  end

  describe "#delete_checklist", :vcr do
    before do
      @checklist = app_client.create_checklist test_card_id, "Autochecklist"
    end

    it "deletes a checklist" do
      app_client.delete_checklist(@checklist.id)

      expect { app_client.checklist(@checklist.id) }.to raise_error(Tacokit::Error::ResourceNotFound)
      assert_requested :delete, trello_url_template("checklists/#{@checklist.id}{?key,token}")
    end
  end
end
